[project]
name = "mcp-server-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[ws]",
]

[tool.uv.sources]
mcp = { git = "https://github.com/openwallet-foundation-labs/mcp-over-tsp-python" }
